import type { CurriculumPackage } from './types'

export const curriculumRegistry: CurriculumPackage[] = [
  {
    id: 'software-engineering',
    name: 'Software Engineering',
    description: 'Transform programming fundamentals into production-ready engineering practice.',
    learningArea: {
      name: 'Software Engineering',
      code: 'SE',
      description: 'Professional software development, systems thinking, and product delivery.',
      status: 'ACTIVE',
      displayOrder: 1,
    },
    learningPaths: [
      { name: 'Software Engineering Beginner', description: 'Foundations pathway for junior developers.', competencies: ['Programming Fundamentals', 'Version Control', 'Object-Oriented Programming', 'Databases', 'REST APIs'] },
      { name: 'Software Engineering Intermediate', description: 'System design and delivery pathway.', competencies: ['Testing', 'CI/CD', 'Software Architecture', 'Deployment', 'Documentation'] },
      { name: 'Software Engineering Advanced', description: 'High-scale architecture and product resilience.', competencies: ['Distributed Systems', 'Performance Optimization', 'Security Engineering', 'Platform Design', 'Technical Leadership'] },
    ],
    competencies: [
      {
        name: 'Programming Fundamentals',
        code: 'SE-COMP-001',
        description: 'Build strong coding foundations using structured reasoning and modern programming languages.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Python', code: 'SE-COMP-001-G1', description: 'Python scripting and application logic.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Java', code: 'SE-COMP-001-G2', description: 'Java syntax and enterprise patterns.', status: 'ACTIVE', sortOrder: 2 },
          { name: 'JavaScript', code: 'SE-COMP-001-G3', description: 'JavaScript and browser fundamentals.', status: 'ACTIVE', sortOrder: 3 },
          { name: 'C#', code: 'SE-COMP-001-G4', description: 'C# development foundations.', status: 'ACTIVE', sortOrder: 4 },
        ],
      },
      {
        name: 'Object-Oriented Programming',
        code: 'SE-COMP-002',
        description: 'Model domain logic using classes, encapsulation, inheritance, and abstraction.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Encapsulation', code: 'SE-COMP-002-G1', description: 'Control visibility and state boundaries.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Inheritance', code: 'SE-COMP-002-G2', description: 'Reuse and specialise behaviour.', status: 'ACTIVE', sortOrder: 2 },
          { name: 'Polymorphism', code: 'SE-COMP-002-G3', description: 'Dynamic behavior through interfaces and overrides.', status: 'ACTIVE', sortOrder: 3 },
        ],
      },
      {
        name: 'Data Structures',
        code: 'SE-COMP-003',
        description: 'Select and apply appropriate data structures for problem solving and performance.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Arrays', code: 'SE-COMP-003-G1', description: 'Ordered collections and indexing.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Trees', code: 'SE-COMP-003-G2', description: 'Hierarchical storage and traversal.', status: 'ACTIVE', sortOrder: 2 },
          { name: 'Graphs', code: 'SE-COMP-003-G3', description: 'Relationships and traversal strategies.', status: 'ACTIVE', sortOrder: 3 },
        ],
      },
      {
        name: 'Version Control',
        code: 'SE-COMP-004',
        description: 'Manage feature delivery, collaboration, and change history with modern version control tools.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Git', code: 'SE-COMP-004-G1', description: 'Repository operations and git workflows.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'GitHub', code: 'SE-COMP-004-G2', description: 'Pull requests, reviews, and collaboration patterns.', status: 'ACTIVE', sortOrder: 2 },
          { name: 'Branching', code: 'SE-COMP-004-G3', description: 'Feature, release, and hotfix branching models.', status: 'ACTIVE', sortOrder: 3 },
        ],
      },
      {
        name: 'REST APIs',
        code: 'SE-COMP-005',
        description: 'Design and integrate clear HTTP-based interfaces and service contracts.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 5,
        groups: [
          { name: 'HTTP Methods', code: 'SE-COMP-005-G1', description: 'GET, POST, PUT, DELETE semantics.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Authentication', code: 'SE-COMP-005-G2', description: 'Keys, JWT, OAuth, and session security.', status: 'ACTIVE', sortOrder: 2 },
          { name: 'API Design', code: 'SE-COMP-005-G3', description: 'Versioning, payloads, and response contracts.', status: 'ACTIVE', sortOrder: 3 },
        ],
      },
    ],
  },
  {
    id: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    description: 'Develop AI systems that reason, learn, and solve practical problems responsibly.',
    learningArea: {
      name: 'Artificial Intelligence',
      code: 'AI',
      description: 'Foundation in AI, reasoning, and data-driven decision systems.',
      status: 'ACTIVE',
      displayOrder: 2,
    },
    learningPaths: [
      { name: 'AI Foundations', description: 'Begin with mathematical and practical AI modeling.', competencies: ['Python', 'Linear Algebra', 'Statistics', 'Machine Learning', 'Model Deployment'] },
      { name: 'AI Productization', description: 'Move from research to deployment and governance.', competencies: ['Deep Learning', 'Computer Vision', 'NLP', 'Responsible AI', 'Model Deployment'] },
    ],
    competencies: [
      {
        name: 'Python',
        code: 'AI-COMP-001',
        description: 'Use Python for data manipulation, experimentation, and model pipelines.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Data Manipulation', code: 'AI-COMP-001-G1', description: 'Pandas and structured data operations.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Notebook Workflow', code: 'AI-COMP-001-G2', description: 'Exploratory analysis and experimentation cycles.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Linear Algebra',
        code: 'AI-COMP-002',
        description: 'Apply vector and matrix reasoning to machine learning algorithms.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Vectors', code: 'AI-COMP-002-G1', description: 'Vector operations and geometry.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Matrices', code: 'AI-COMP-002-G2', description: 'Transformations and linear systems.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Statistics',
        code: 'AI-COMP-003',
        description: 'Use probability and inference to interpret model behavior and evaluation.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Probability', code: 'AI-COMP-003-G1', description: 'Distribution and uncertainty modeling.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Hypothesis Testing', code: 'AI-COMP-003-G2', description: 'Statistical validation and significance.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Machine Learning',
        code: 'AI-COMP-004',
        description: 'Train, evaluate, and compare models for predictive tasks.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Supervised Learning', code: 'AI-COMP-004-G1', description: 'Classification and regression models.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Feature Engineering', code: 'AI-COMP-004-G2', description: 'Transforming input variables for model success.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Deep Learning',
        code: 'AI-COMP-005',
        description: 'Apply neural networks to complex data and representation learning problems.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 5,
        groups: [
          { name: 'Neural Networks', code: 'AI-COMP-005-G1', description: 'Layers, activations, and forward passes.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Optimization', code: 'AI-COMP-005-G2', description: 'Backpropagation and training strategy.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'data-science',
    name: 'Data Science',
    description: 'Build evidence-driven insight pipelines from raw data to business action.',
    learningArea: {
      name: 'Data Science',
      code: 'DS',
      description: 'Analytics, modeling, and data-driven decision support.',
      status: 'ACTIVE',
      displayOrder: 3,
    },
    learningPaths: [
      { name: 'Data Analyst Foundation', description: 'Explore the full data lifecycle from cleaning to storytelling.', competencies: ['SQL', 'Data Wrangling', 'Visualization', 'Statistical Analysis', 'Dashboarding'] },
      { name: 'Data Science Practitioner', description: 'Build predictive and scientific data reasoning capabilities.', competencies: ['Machine Learning', 'Experiment Design', 'Feature Engineering', 'Model Evaluation', 'Communication'] },
    ],
    competencies: [
      {
        name: 'SQL',
        code: 'DS-COMP-001',
        description: 'Query and transform structured datasets using SQL.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Querying', code: 'DS-COMP-001-G1', description: 'SELECT, filters, joins, and subqueries.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Aggregation', code: 'DS-COMP-001-G2', description: 'GROUP BY, rollups, and summarisation.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Data Wrangling',
        code: 'DS-COMP-002',
        description: 'Clean, standardize, and structure inconsistent data sources.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Cleaning', code: 'DS-COMP-002-G1', description: 'Handle missing values and inconsistencies.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Normalization', code: 'DS-COMP-002-G2', description: 'Standardize schema and data definitions.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Visualization',
        code: 'DS-COMP-003',
        description: 'Represent patterns and findings with clear, defensible visual narratives.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Charts', code: 'DS-COMP-003-G1', description: 'Bar, line, scatter, and distribution views.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Dashboards', code: 'DS-COMP-003-G2', description: 'Operational and executive reporting views.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Statistical Analysis',
        code: 'DS-COMP-004',
        description: 'Apply statistical reasoning to measured outcomes and trends.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Correlation', code: 'DS-COMP-004-G1', description: 'Assess variables and association.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Regression', code: 'DS-COMP-004-G2', description: 'Model relationships and effect sizes.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'cyber-security',
    name: 'Cyber Security',
    description: 'Protect digital systems, data, and users through defensive engineering and incident readiness.',
    learningArea: {
      name: 'Cyber Security',
      code: 'CS',
      description: 'Security operations, governance, and threat defense.',
      status: 'ACTIVE',
      displayOrder: 4,
    },
    learningPaths: [
      { name: 'Security Operations', description: 'Protect systems and monitor threats in production.', competencies: ['Network Security', 'Threat Analysis', 'Vulnerability Management', 'Incident Response', 'Security Governance'] },
      { name: 'Security Engineering', description: 'Design secure systems and controls from the beginning.', competencies: ['Application Security', 'Identity Access Management', 'Encryption', 'Security Testing', 'Compliance'] },
    ],
    competencies: [
      {
        name: 'Network Security',
        code: 'CS-COMP-001',
        description: 'Secure networks and evaluate traffic across services and devices.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Firewalls', code: 'CS-COMP-001-G1', description: 'Policy enforcement and access control.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Segmentation', code: 'CS-COMP-001-G2', description: 'Isolate systems and reduce lateral movement.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Threat Analysis',
        code: 'CS-COMP-002',
        description: 'Identify attacker patterns, risk indicators, and defensive priorities.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Threat Intelligence', code: 'CS-COMP-002-G1', description: 'Track and categorise adversary activity.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Risk Assessment', code: 'CS-COMP-002-G2', description: 'Prioritize assets, impact, and exposure.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Vulnerability Management',
        code: 'CS-COMP-003',
        description: 'Discover, assess, and remediate weaknesses before exploitation.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Scanning', code: 'CS-COMP-003-G1', description: 'Identify exposed issues and misconfigurations.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Patching', code: 'CS-COMP-003-G2', description: 'Prioritize and track patch remediation.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Incident Response',
        code: 'CS-COMP-004',
        description: 'Respond to security events using structured investigation and recovery steps.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Containment', code: 'CS-COMP-004-G1', description: 'Limit blast radius and isolate assets.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Recovery', code: 'CS-COMP-004-G2', description: 'Restore trust and declare remediation status.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'cloud-computing',
    name: 'Cloud Computing',
    description: 'Design resilient cloud-native systems across compute, storage, networking, and automation.',
    learningArea: {
      name: 'Cloud Computing',
      code: 'CC',
      description: 'Cloud architecture and platform operations.',
      status: 'ACTIVE',
      displayOrder: 5,
    },
    learningPaths: [
      { name: 'Cloud Foundations', description: 'Understand core cloud building blocks for modern services.', competencies: ['Cloud Fundamentals', 'Compute Services', 'Networking in the Cloud', 'Identity & Access', 'Monitoring'] },
      { name: 'Cloud Platform Engineering', description: 'Deliver highly available and governed cloud deployments.', competencies: ['IaC', 'Containers', 'Serverless', 'Security Posture', 'Cost Optimization'] },
    ],
    competencies: [
      {
        name: 'Cloud Fundamentals',
        code: 'CC-COMP-001',
        description: 'Understand shared-responsibility models, scaling, and service categories.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Compute', code: 'CC-COMP-001-G1', description: 'Virtual machines and managed compute.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Storage', code: 'CC-COMP-001-G2', description: 'Volumes, object stores, and data durability.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Compute Services',
        code: 'CC-COMP-002',
        description: 'Deploy and scale services using cloud-native compute patterns.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Containers', code: 'CC-COMP-002-G1', description: 'Run workloads with portable isolation.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Serverless', code: 'CC-COMP-002-G2', description: 'Event-driven execution and autoscaling.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Networking in the Cloud',
        code: 'CC-COMP-003',
        description: 'Configure secure connectivity, routing, and service exposure.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'VPCs', code: 'CC-COMP-003-G1', description: 'Private network design and segmentation.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Load Balancing', code: 'CC-COMP-003-G2', description: 'Traffic distribution and health checks.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Infrastructure as Code',
        code: 'CC-COMP-004',
        description: 'Provision and manage cloud infrastructure with repeatable automation.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Terraform', code: 'CC-COMP-004-G1', description: 'Declarative infrastructure provisioning.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'CloudFormation', code: 'CC-COMP-004-G2', description: 'Template-based cloud management.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'networking',
    name: 'Networking',
    description: 'Operate network infrastructure for resilient and secure communications.',
    learningArea: {
      name: 'Networking',
      code: 'NET',
      description: 'Connectivity, infrastructure design, and network operations.',
      status: 'ACTIVE',
      displayOrder: 6,
    },
    learningPaths: [
      { name: 'Networking Fundamentals', description: 'Understand the core internet and local network layers.', competencies: ['TCP/IP', 'Switching', 'Routing', 'Wireless Networking', 'Troubleshooting'] },
      { name: 'Infrastructure Operations', description: 'Keep enterprise networks secure and stable.', competencies: ['Network Security', 'Monitoring', 'Automation', 'Performance Tuning', 'Documentation'] },
    ],
    competencies: [
      {
        name: 'TCP/IP',
        code: 'NET-COMP-001',
        description: 'Understand core internet protocols and data transport models.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'IPv4', code: 'NET-COMP-001-G1', description: 'Addressing and packet forwarding.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'IPv6', code: 'NET-COMP-001-G2', description: 'Next generation addressing and transition.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Switching',
        code: 'NET-COMP-002',
        description: 'Configure and troubleshoot local Ethernet and VLAN-based switching.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'VLANs', code: 'NET-COMP-002-G1', description: 'Segmentation and network isolation.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'STP', code: 'NET-COMP-002-G2', description: 'Loop prevention and redundancy.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Routing',
        code: 'NET-COMP-003',
        description: 'Design and maintain path selection across networks and subnets.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Static Routing', code: 'NET-COMP-003-G1', description: 'Manual route design and control.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Dynamic Routing', code: 'NET-COMP-003-G2', description: 'OSPF and routing protocol behavior.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Troubleshooting',
        code: 'NET-COMP-004',
        description: 'Diagnose connectivity issues using layered network reasoning.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Packet Analysis', code: 'NET-COMP-004-G1', description: 'Use traffic inspection to isolate failures.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Performance Review', code: 'NET-COMP-004-G2', description: 'Diagnose latency and throughput constraints.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'Bridge development and operations through automation, reliability, and delivery excellence.',
    learningArea: {
      name: 'DevOps',
      code: 'DO',
      description: 'Delivery automation, operations, and platform reliability.',
      status: 'ACTIVE',
      displayOrder: 7,
    },
    learningPaths: [
      { name: 'DevOps Essentials', description: 'Deliver code faster with automation and observability.', competencies: ['CI/CD', 'Containerization', 'Monitoring', 'Infrastructure Automation', 'Documentation'] },
      { name: 'Platform Reliability', description: 'Increase resilience and service health at scale.', competencies: ['Incident Response', 'Scaling', 'SRE Practices', 'Automation', 'Security Hardening'] },
    ],
    competencies: [
      {
        name: 'CI/CD',
        code: 'DO-COMP-001',
        description: 'Automate build, test, and deployment workflows with predictability.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'GitHub Actions', code: 'DO-COMP-001-G1', description: 'Workflow automation for pull requests and deployments.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Deployment Pipelines', code: 'DO-COMP-001-G2', description: 'Controlled rollout and validation flows.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Containerization',
        code: 'DO-COMP-002',
        description: 'Package and run applications consistently across environments.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Docker', code: 'DO-COMP-002-G1', description: 'Container build and runtime management.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Orchestration', code: 'DO-COMP-002-G2', description: 'Deploy and manage service layers.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Monitoring',
        code: 'DO-COMP-003',
        description: 'Observe system health and detect issues before they affect users.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Logs', code: 'DO-COMP-003-G1', description: 'Capture and review operational signals.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Metrics', code: 'DO-COMP-003-G2', description: 'Measure trends, SLIs, and resource usage.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Infrastructure Automation',
        code: 'DO-COMP-004',
        description: 'Reduce manual operations through repeatable provisioning and configuration.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Configuration Management', code: 'DO-COMP-004-G1', description: 'Managed, versioned system configuration.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Provisioning', code: 'DO-COMP-004-G2', description: 'Environment creation at scale.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'mobile-development',
    name: 'Mobile Development',
    description: 'Build mobile experiences that are performant, usable, and production-ready.',
    learningArea: {
      name: 'Mobile Development',
      code: 'MD',
      description: 'App design, implementation, and mobile platform workflows.',
      status: 'ACTIVE',
      displayOrder: 8,
    },
    learningPaths: [
      { name: 'Mobile Foundations', description: 'Learn app architecture and user experience design.', competencies: ['Mobile UI Design', 'State Management', 'Networking', 'Testing', 'App Deployment'] },
      { name: 'Cross-Platform Engineering', description: 'Build mobile apps across device ecosystems.', competencies: ['Flutter', 'React Native', 'Native APIs', 'Performance', 'App Store Publishing'] },
    ],
    competencies: [
      {
        name: 'Mobile UI Design',
        code: 'MD-COMP-001',
        description: 'Design interfaces optimized for touch workflows and mobile constraints.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Layouts', code: 'MD-COMP-001-G1', description: 'Responsive screen composition.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Navigation', code: 'MD-COMP-001-G2', description: 'Flow control and user navigation patterns.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'State Management',
        code: 'MD-COMP-002',
        description: 'Maintain reliable application state across screens and lifecycle events.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Local State', code: 'MD-COMP-002-G1', description: 'Widget and screen-level state logic.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Shared State', code: 'MD-COMP-002-G2', description: 'Cross-screen data management.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Native APIs',
        code: 'MD-COMP-003',
        description: 'Integrate platform features such as camera, storage, notifications, and sensors.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Permissions', code: 'MD-COMP-003-G1', description: 'Runtime privileges and user consent.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Device Features', code: 'MD-COMP-003-G2', description: 'Camera, GPS, and push-driven experiences.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'App Deployment',
        code: 'MD-COMP-004',
        description: 'Package, test, and publish applications to customers and stores.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'App Store', code: 'MD-COMP-004-G1', description: 'Submission and sign-off flow.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Release Management', code: 'MD-COMP-004-G2', description: 'Versioning and rollout strategy.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'web-development',
    name: 'Web Development',
    description: 'Compose modern web interfaces and application architectures for digital products.',
    learningArea: {
      name: 'Web Development',
      code: 'WD',
      description: 'Frontend, backend, and full-stack web product delivery.',
      status: 'ACTIVE',
      displayOrder: 9,
    },
    learningPaths: [
      { name: 'Frontend Foundations', description: 'Build polished and accessible client experiences.', competencies: ['HTML & CSS', 'JavaScript', 'React', 'Accessibility', 'Performance'] },
      { name: 'Full-Stack Delivery', description: 'Deliver complete services from API to interface.', competencies: ['REST APIs', 'Databases', 'Authentication', 'Testing', 'Deployment'] },
    ],
    competencies: [
      {
        name: 'HTML & CSS',
        code: 'WD-COMP-001',
        description: 'Create semantic, accessible, and responsive interfaces.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Semantic Markup', code: 'WD-COMP-001-G1', description: 'Document structure and accessible content.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Responsive Layout', code: 'WD-COMP-001-G2', description: 'Fluid layouts across device sizes.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'JavaScript',
        code: 'WD-COMP-002',
        description: 'Build interactive client-side logic with modern JavaScript patterns.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'DOM', code: 'WD-COMP-002-G1', description: 'Document manipulation and browser events.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Async Programming', code: 'WD-COMP-002-G2', description: 'Promises, async/await, and fetch flows.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'React',
        code: 'WD-COMP-003',
        description: 'Compose component-driven interfaces and application state flows.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Components', code: 'WD-COMP-003-G1', description: 'Reusable UI structures and composition.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Hooks', code: 'WD-COMP-003-G2', description: 'Lifecycle and state-driven logic.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Accessibility',
        code: 'WD-COMP-004',
        description: 'Ensure content is inclusive and usable for diverse users.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Keyboard Access', code: 'WD-COMP-004-G1', description: 'Focus navigation and key interactions.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Semantics', code: 'WD-COMP-004-G2', description: 'Meaningful labels, roles, and structure.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'ui-ux-design',
    name: 'UI/UX Design',
    description: 'Create thoughtful user-centered digital experiences and design systems.',
    learningArea: {
      name: 'UI/UX Design',
      code: 'UIX',
      description: 'Design research, interface design, and interaction systems.',
      status: 'ACTIVE',
      displayOrder: 10,
    },
    learningPaths: [
      { name: 'UX Foundations', description: 'Learn user research and concept creation.', competencies: ['User Research', 'Wireframing', 'Information Architecture', 'Interaction Design', 'Usability Testing'] },
      { name: 'Design Systems', description: 'Create scalable visual systems and product consistency.', competencies: ['Visual Design', 'Design Systems', 'Prototyping', 'Accessibility', 'Design Handoff'] },
    ],
    competencies: [
      {
        name: 'User Research',
        code: 'UIX-COMP-001',
        description: 'Capture needs and behaviors through observation and structured inquiry.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Interviews', code: 'UIX-COMP-001-G1', description: 'Gather qualitative feedback from users.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Surveys', code: 'UIX-COMP-001-G2', description: 'Validate patterns and preferences at scale.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Wireframing',
        code: 'UIX-COMP-002',
        description: 'Sketch interaction flows and interface structure before detailed design.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Low Fidelity', code: 'UIX-COMP-002-G1', description: 'Quick concept exploration and iteration.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'High Fidelity', code: 'UIX-COMP-002-G2', description: 'Detailed interface characterization.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Interaction Design',
        code: 'UIX-COMP-003',
        description: 'Shape how users navigate, complete actions, and receive feedback.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Gestures', code: 'UIX-COMP-003-G1', description: 'Touch and motion patterns.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Feedback', code: 'UIX-COMP-003-G2', description: 'Confirmation states and user guidance.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Design Systems',
        code: 'UIX-COMP-004',
        description: 'Create reusable design foundations that maintain product consistency.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Tokens', code: 'UIX-COMP-004-G1', description: 'Colors, spacing, typography, and scales.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Components', code: 'UIX-COMP-004-G2', description: 'Reusable patterns and states.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'game-development',
    name: 'Game Development',
    description: 'Design interactive game systems, gameplay loops, and immersive experiences.',
    learningArea: {
      name: 'Game Development',
      code: 'GD',
      description: 'Gameplay design, systems, and real-time interaction.',
      status: 'ACTIVE',
      displayOrder: 11,
    },
    learningPaths: [
      { name: 'Gameplay Programming', description: 'Understand game systems and loops.', competencies: ['Game Design', 'Gameplay Programming', 'Physics', 'Rendering', 'Testing'] },
      { name: 'Production Pipeline', description: 'Prepare games for release and user engagement.', competencies: ['Asset Management', 'Audio Design', 'Performance', 'Optimization', 'Deployment'] },
    ],
    competencies: [
      {
        name: 'Game Design',
        code: 'GD-COMP-001',
        description: 'Shape interactive mechanics, goals, and player engagement loops.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Mechanics', code: 'GD-COMP-001-G1', description: 'Rules and interactions that create play.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Progression', code: 'GD-COMP-001-G2', description: 'Player advancement and challenge curves.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Gameplay Programming',
        code: 'GD-COMP-002',
        description: 'Implement character movement, interaction systems, and state transitions.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Controllers', code: 'GD-COMP-002-G1', description: 'Input and movement handling.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Events', code: 'GD-COMP-002-G2', description: 'Triggering logic and reactive systems.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Physics',
        code: 'GD-COMP-003',
        description: 'Apply realistic or stylized motion and collision behavior.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Collisions', code: 'GD-COMP-003-G1', description: 'Object interaction and boundaries.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Forces', code: 'GD-COMP-003-G2', description: 'Movement, gravity, and momentum models.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Rendering',
        code: 'GD-COMP-004',
        description: 'Render scenes, effects, and visual polish within performance constraints.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Shaders', code: 'GD-COMP-004-G1', description: 'Visual effects and material behavior.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Lighting', code: 'GD-COMP-004-G2', description: 'Atmosphere and scene composition.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'embedded-systems',
    name: 'Embedded Systems',
    description: 'Design reliable systems that interact with hardware, sensors, and real-time constraints.',
    learningArea: {
      name: 'Embedded Systems',
      code: 'ES',
      description: 'Hardware-aware software engineering and systems integration.',
      status: 'ACTIVE',
      displayOrder: 12,
    },
    learningPaths: [
      { name: 'Embedded Foundations', description: 'Understand hardware-software integration and control loops.', competencies: ['C/C++', 'Microcontrollers', 'Sensors', 'Real-Time Systems', 'Debugging'] },
      { name: 'Device Engineering', description: 'Deliver stable, testable embedded products.', competencies: ['Communication Protocols', 'Power Management', 'Testing', 'Optimization', 'System Integration'] },
    ],
    competencies: [
      {
        name: 'C/C++',
        code: 'ES-COMP-001',
        description: 'Develop efficient low-level logic for constrained environments.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Memory', code: 'ES-COMP-001-G1', description: 'Pointers, allocation, and resource management.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Control Flow', code: 'ES-COMP-001-G2', description: 'Event-driven and deterministic logic.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Microcontrollers',
        code: 'ES-COMP-002',
        description: 'Program devices with limited resources and precise timing demands.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'GPIO', code: 'ES-COMP-002-G1', description: 'Digital signal communication and control.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Timers', code: 'ES-COMP-002-G2', description: 'Time-based logic and scheduling.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Sensors',
        code: 'ES-COMP-003',
        description: 'Interpret readings from hardware inputs and environmental devices.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Analog Input', code: 'ES-COMP-003-G1', description: 'Measure varying electrical signals.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Digital Sensors', code: 'ES-COMP-003-G2', description: 'Read discrete device state changes.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Real-Time Systems',
        code: 'ES-COMP-004',
        description: 'Deliver predictable behavior under strict timing and availability constraints.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Scheduling', code: 'ES-COMP-004-G1', description: 'Task ordering and deadline handling.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Latency', code: 'ES-COMP-004-G2', description: 'Response timing and throughput optimization.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'business-analysis',
    name: 'Business Analysis',
    description: 'Align technology and operations with business goals and measurable outcomes.',
    learningArea: {
      name: 'Business Analysis',
      code: 'BA',
      description: 'Business process optimization and decision analysis.',
      status: 'ACTIVE',
      displayOrder: 13,
    },
    learningPaths: [
      { name: 'Business Analyst Foundation', description: 'Translate stakeholder needs into systems and process change.', competencies: ['Requirements Analysis', 'Process Modeling', 'Stakeholder Communication', 'Solution Evaluation', 'Change Management'] },
      { name: 'Operations Improvement', description: 'Deliver process value through analysis and optimization.', competencies: ['Data Analysis', 'Business Rules', 'KPIs', 'Risk Analysis', 'Documentation'] },
    ],
    competencies: [
      {
        name: 'Requirements Analysis',
        code: 'BA-COMP-001',
        description: 'Convert stakeholder needs into actionable and testable business requirements.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Stakeholder Needs', code: 'BA-COMP-001-G1', description: 'Capture operational and strategic goals.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Acceptance Criteria', code: 'BA-COMP-001-G2', description: 'Define measurable completion conditions.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Process Modeling',
        code: 'BA-COMP-002',
        description: 'Map current and target workflows to identify improvement opportunities.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'As-Is Processes', code: 'BA-COMP-002-G1', description: 'Current-state analysis and bottleneck identification.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'To-Be Processes', code: 'BA-COMP-002-G2', description: 'Future-state design and optimization.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Stakeholder Communication',
        code: 'BA-COMP-003',
        description: 'Coordinate alignment between technical teams and business leaders.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Presentations', code: 'BA-COMP-003-G1', description: 'Summarize findings for decision-makers.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Negotiation', code: 'BA-COMP-003-G2', description: 'Resolve trade-offs and prioritize outcomes.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Solution Evaluation',
        code: 'BA-COMP-004',
        description: 'Assess proposed solutions against business value, risk, and feasibility.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'ROI', code: 'BA-COMP-004-G1', description: 'Measure commercial impact and viability.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Trade-Off Analysis', code: 'BA-COMP-004-G2', description: 'Balance cost, effort, and value.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'project-management',
    name: 'Project Management',
    description: 'Drive delivery through planning, governance, and risk-aware execution.',
    learningArea: {
      name: 'Project Management',
      code: 'PM',
      description: 'Portfolio coordination, planning, and risk governance.',
      status: 'ACTIVE',
      displayOrder: 14,
    },
    learningPaths: [
      { name: 'Project Foundations', description: 'Learn to plan and coordinate delivery.', competencies: ['Planning', 'Scheduling', 'Risk Management', 'Stakeholder Engagement', 'Delivery Tracking'] },
      { name: 'Portfolio Leadership', description: 'Govern complex programs and cross-functional work.', competencies: ['Governance', 'Budgeting', 'Prioritization', 'Reporting', 'Change Leadership'] },
    ],
    competencies: [
      {
        name: 'Planning',
        code: 'PM-COMP-001',
        description: 'Structure work into achievable phases with measurable outcomes.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Roadmaps', code: 'PM-COMP-001-G1', description: 'Define high-level delivery direction.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Work Breakdown', code: 'PM-COMP-001-G2', description: 'Decompose scope into executable tasks.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Scheduling',
        code: 'PM-COMP-002',
        description: 'Sequence tasks and dependencies for predictable delivery.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Dependencies', code: 'PM-COMP-002-G1', description: 'Map critical paths and limiting sequences.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Milestones', code: 'PM-COMP-002-G2', description: 'Track checkpoints and phase completion.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Risk Management',
        code: 'PM-COMP-003',
        description: 'Identify, assess, and respond to delivery risks proactively.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Risk Register', code: 'PM-COMP-003-G1', description: 'Document and review emerging threats.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Mitigation', code: 'PM-COMP-003-G2', description: 'Plan active control actions and escalation.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Stakeholder Engagement',
        code: 'PM-COMP-004',
        description: 'Align expectations, communicate progress, and manage decision makers.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Status Reporting', code: 'PM-COMP-004-G1', description: 'Create timely progress communication.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Escalation', code: 'PM-COMP-004-G2', description: 'Trigger interventions and sponsor support.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    description: 'Design audiences, campaigns, and engagement strategies for digital channels.',
    learningArea: {
      name: 'Digital Marketing',
      code: 'DM',
      description: 'Campaign planning, customer engagement, and measurement.',
      status: 'ACTIVE',
      displayOrder: 15,
    },
    learningPaths: [
      { name: 'Marketing Basics', description: 'Build customer strategy and channel understanding.', competencies: ['Campaign Strategy', 'Content Marketing', 'SEO', 'Analytics', 'Brand Messaging'] },
      { name: 'Digital Growth', description: 'Scale campaigns with measurement and optimization.', competencies: ['Performance Marketing', 'CRM', 'A/B Testing', 'Attribution', 'Conversion Optimization'] },
    ],
    competencies: [
      {
        name: 'Campaign Strategy',
        code: 'DM-COMP-001',
        description: 'Define target audience, channels, and objectives for customer acquisition.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Audience Segmentation', code: 'DM-COMP-001-G1', description: 'Group users by behavior and need.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Channel Planning', code: 'DM-COMP-001-G2', description: 'Choose the right channel mix for objectives.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Content Marketing',
        code: 'DM-COMP-002',
        description: 'Create strategic content that moves users through the funnel.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Editorial Planning', code: 'DM-COMP-002-G1', description: 'Map content calendars and themes.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Copywriting', code: 'DM-COMP-002-G2', description: 'Authors effective and conversion-minded messaging.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'SEO',
        code: 'DM-COMP-003',
        description: 'Improve discoverability through keyword, content, and technical optimization.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Keyword Research', code: 'DM-COMP-003-G1', description: 'Identify high-value marketing demand.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'On-Page Optimization', code: 'DM-COMP-003-G2', description: 'Improve page elements and content relevance.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Analytics',
        code: 'DM-COMP-004',
        description: 'Track campaign impact and convert data to optimization decisions.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Attribution', code: 'DM-COMP-004-G1', description: 'Link effort to customer response.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Funnel Analysis', code: 'DM-COMP-004-G2', description: 'Examine conversion journeys and drop-offs.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    description: 'Create visual communication systems that support brands, products, and learning experiences.',
    learningArea: {
      name: 'Graphic Design',
      code: 'GDG',
      description: 'Visual storytelling, design systems, and production craft.',
      status: 'ACTIVE',
      displayOrder: 16,
    },
    learningPaths: [
      { name: 'Visual Design', description: 'Develop a strong visual and brand communication toolkit.', competencies: ['Visual Composition', 'Typography', 'Color Theory', 'Brand Identity', 'Production'] },
      { name: 'Design Production', description: 'Translate design into reusable, accessible assets.', competencies: ['Layout Systems', 'Image Editing', 'Design Handoff', 'Accessibility', 'Asset Management'] },
    ],
    competencies: [
      {
        name: 'Visual Composition',
        code: 'GDG-COMP-001',
        description: 'Arrange graphic elements to guide perceived hierarchy and attention.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Layout', code: 'GDG-COMP-001-G1', description: 'Arrange blocks, balance, and rhythm.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Hierarchy', code: 'GDG-COMP-001-G2', description: 'Signal emphasis and importance visually.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Typography',
        code: 'GDG-COMP-002',
        description: 'Use type systems to build comprehension and brand voice.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Font Pairing', code: 'GDG-COMP-002-G1', description: 'Combine typefaces effectively.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Readability', code: 'GDG-COMP-002-G2', description: 'Improve legibility and alignment.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Color Theory',
        code: 'GDG-COMP-003',
        description: 'Apply color relationships to improve mood, contrast, and meaning.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Palettes', code: 'GDG-COMP-003-G1', description: 'Create harmonized themes.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Accessibility', code: 'GDG-COMP-003-G2', description: 'Maintain color contrast and legibility.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Brand Identity',
        code: 'GDG-COMP-004',
        description: 'Build memorable visual systems that communicate intent and consistency.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Logo Systems', code: 'GDG-COMP-004-G1', description: 'Represent identity through visual marks.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Brand Assets', code: 'GDG-COMP-004-G2', description: 'Package reusable identity components.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'computer-support-it',
    name: 'Computer Support & IT',
    description: 'Deliver dependable technical support and user-focused IT operations.',
    learningArea: {
      name: 'Computer Support & IT',
      code: 'CSIT',
      description: 'Support operations, device management, and service delivery.',
      status: 'ACTIVE',
      displayOrder: 17,
    },
    learningPaths: [
      { name: 'IT Support Essentials', description: 'Resolve technical issues with empathy and method.', competencies: ['Device Troubleshooting', 'User Support', 'Networking Basics', 'Ticketing', 'Security Awareness'] },
      { name: 'Service Operations', description: 'Run effective support workflows and service quality checks.', competencies: ['Asset Management', 'Remote Support', 'Documentation', 'Monitoring', 'Escalation'] },
    ],
    competencies: [
      {
        name: 'Device Troubleshooting',
        code: 'CSIT-COMP-001',
        description: 'Diagnose and repair common hardware and software issues.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Hardware', code: 'CSIT-COMP-001-G1', description: 'Assess device faults and reliability issues.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Software', code: 'CSIT-COMP-001-G2', description: 'Fix configuration and operating system problems.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'User Support',
        code: 'CSIT-COMP-002',
        description: 'Support users using clear communication and structured resolution flow.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Helpdesk', code: 'CSIT-COMP-002-G1', description: 'Handle support tickets and triage.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Remote Support', code: 'CSIT-COMP-002-G2', description: 'Resolve issues through guided assistance.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Asset Management',
        code: 'CSIT-COMP-003',
        description: 'Track hardware inventory, lifecycle, and maintenance changes.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Inventory', code: 'CSIT-COMP-003-G1', description: 'Document physical and virtual equipment.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Lifecycle', code: 'CSIT-COMP-003-G2', description: 'Manage procurement, updates, and disposal.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Security Awareness',
        code: 'CSIT-COMP-004',
        description: 'Protect users and devices from common operational risks and policy violations.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Phishing', code: 'CSIT-COMP-004-G1', description: 'Recognize suspicious emails and behavior.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Access Safety', code: 'CSIT-COMP-004-G2', description: 'Protect accounts and devices with safe usage habits.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'data-engineering',
    name: 'Data Engineering',
    description: 'Build reliable data systems, pipelines, and infrastructure for modern analytics.',
    learningArea: {
      name: 'Data Engineering',
      code: 'DE',
      description: 'Data architecture, extraction, and trustworthy pipelines.',
      status: 'ACTIVE',
      displayOrder: 18,
    },
    learningPaths: [
      { name: 'Pipeline Fundamentals', description: 'Collect and move data reliably from source to storage.', competencies: ['SQL', 'ETL', 'Data Modeling', 'Data Warehousing', 'Monitoring'] },
      { name: 'Data Platform Operations', description: 'Run robust data services and maintain quality.', competencies: ['Streaming', 'Automation', 'Data Quality', 'Performance Tuning', 'Governance'] },
    ],
    competencies: [
      {
        name: 'ETL',
        code: 'DE-COMP-001',
        description: 'Extract, transform, and load data from source systems to analytical destinations.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Extraction', code: 'DE-COMP-001-G1', description: 'Read source data consistently.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Transformation', code: 'DE-COMP-001-G2', description: 'Normalize and clean values for downstream use.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Data Modeling',
        code: 'DE-COMP-002',
        description: 'Design clean, scalable, and queryable storage structures.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Relational Models', code: 'DE-COMP-002-G1', description: 'Create normalized and performant tables.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Dimensional Models', code: 'DE-COMP-002-G2', description: 'Support analytics and reporting workloads.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Data Warehousing',
        code: 'DE-COMP-003',
        description: 'Store historical and operational data for structured analysis.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Fact Tables', code: 'DE-COMP-003-G1', description: 'Capture transactional metrics and grain.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Dimension Tables', code: 'DE-COMP-003-G2', description: 'Describe context and attribution.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Data Quality',
        code: 'DE-COMP-004',
        description: 'Validate accuracy, completeness, and consistency across pipelines.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Validation', code: 'DE-COMP-004-G1', description: 'Assess if data matches expected rules.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Observability', code: 'DE-COMP-004-G2', description: 'Assess freshness, quality, and anomaly patterns.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Develop and evaluate production-grade predictive systems and decision models.',
    learningArea: {
      name: 'Machine Learning',
      code: 'ML',
      description: 'Model design, optimization, and deployment for intelligent systems.',
      status: 'ACTIVE',
      displayOrder: 19,
    },
    learningPaths: [
      { name: 'ML Foundations', description: 'Understand model training and evaluation.', competencies: ['Python', 'Statistics', 'Feature Engineering', 'Model Training', 'Evaluation'] },
      { name: 'ML Production', description: 'Deploy reliable and measurable model systems.', competencies: ['MLOps', 'Model Deployment', 'Bias Review', 'Monitoring', 'Responsible AI'] },
    ],
    competencies: [
      {
        name: 'Feature Engineering',
        code: 'ML-COMP-001',
        description: 'Construct inputs that reveal useful patterns for model learning.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Selection', code: 'ML-COMP-001-G1', description: 'Choose the most valuable variables.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Transformation', code: 'ML-COMP-001-G2', description: 'Scale, encode, and combine inputs.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Model Training',
        code: 'ML-COMP-002',
        description: 'Fit models to patterns in data using appropriate algorithms and costs.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'Algorithms', code: 'ML-COMP-002-G1', description: 'Choose and compare learning methods.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Hyperparameters', code: 'ML-COMP-002-G2', description: 'Tune training settings for model quality.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Model Evaluation',
        code: 'ML-COMP-003',
        description: 'Measure predictive quality and business impact with evidence.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Metrics', code: 'ML-COMP-003-G1', description: 'Accuracy, recall, precision, and loss.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Validation', code: 'ML-COMP-003-G2', description: 'Generalization through train/validation/test splits.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Responsible AI',
        code: 'ML-COMP-004',
        description: 'Assess fairness, explainability, and operational impact of AI decisions.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Bias Review', code: 'ML-COMP-004-G1', description: 'Examine model behavior for disparate impact.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Explainability', code: 'ML-COMP-004-G2', description: 'Explain model outputs to stakeholders.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
  {
    id: 'quality-assurance',
    name: 'Quality Assurance',
    description: 'Ensure digital products are reliable, testable, safe, and fit for user needs.',
    learningArea: {
      name: 'Quality Assurance',
      code: 'QA',
      description: 'Testing strategy, quality engineering, and release confidence.',
      status: 'ACTIVE',
      displayOrder: 20,
    },
    learningPaths: [
      { name: 'QA Foundations', description: 'Build quality thinking across product lifecycle.', competencies: ['Testing Fundamentals', 'Automation', 'Bug Reporting', 'Regression', 'Release Readiness'] },
      { name: 'Quality Engineering', description: 'Design quality into delivery through strategy and automation.', competencies: ['Test Strategy', 'CI/CD Integration', 'Performance Testing', 'Security Testing', 'Metrics'] },
    ],
    competencies: [
      {
        name: 'Testing Fundamentals',
        code: 'QA-COMP-001',
        description: 'Understand how tests validate behavior and reduce risk.',
        difficulty: 'BEGINNER',
        status: 'ACTIVE',
        sortOrder: 1,
        groups: [
          { name: 'Manual Testing', code: 'QA-COMP-001-G1', description: 'Exercise features and document observed behavior.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Test Cases', code: 'QA-COMP-001-G2', description: 'Define clear, repeatable validation steps.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Automation',
        code: 'QA-COMP-002',
        description: 'Automate repetitive validation and feedback loops through tooling.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 2,
        groups: [
          { name: 'UI Automation', code: 'QA-COMP-002-G1', description: 'Automated interaction validation for user flows.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'API Testing', code: 'QA-COMP-002-G2', description: 'Validate service behavior and contract compliance.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Bug Reporting',
        code: 'QA-COMP-003',
        description: 'Communicate defects clearly so they can be reproduced and resolved.',
        difficulty: 'INTERMEDIATE',
        status: 'ACTIVE',
        sortOrder: 3,
        groups: [
          { name: 'Root Cause', code: 'QA-COMP-003-G1', description: 'Connect symptoms to underlying failure patterns.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Evidence', code: 'QA-COMP-003-G2', description: 'Capture steps, data, and conditions for debugging.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
      {
        name: 'Performance Testing',
        code: 'QA-COMP-004',
        description: 'Assess speed, reliability, and scalability under realistic load.',
        difficulty: 'ADVANCED',
        status: 'ACTIVE',
        sortOrder: 4,
        groups: [
          { name: 'Load Testing', code: 'QA-COMP-004-G1', description: 'Measure user load and response characteristics.', status: 'ACTIVE', sortOrder: 1 },
          { name: 'Stress Testing', code: 'QA-COMP-004-G2', description: 'Test the system near failure thresholds.', status: 'ACTIVE', sortOrder: 2 },
        ],
      },
    ],
  },
]

export function getCurriculumRegistry() {
  return curriculumRegistry
}

export function getCurriculumPackageById(id: string) {
  return curriculumRegistry.find((pkg) => pkg.id === id) ?? null
}
